// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crpt.Data;

namespace crpt.Migrations
{
    [DbContext(typeof(CryptoContext))]
    [Migration("20211101105723_dataupdate")]
    partial class dataupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("crpt.Models.Datum", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("circulating_supply")
                        .HasColumnType("REAL");

                    b.Property<int>("cmc_rank")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("max_supply")
                        .HasColumnType("REAL");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("symbol")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Datum");
                });
#pragma warning restore 612, 618
        }
    }
}
